routes/web.php
<?php

Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category'); //отобраэение категорий
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article'); // отображение новостей
Route::get('/blog/author/', 'BlogController@author')->name('author'); // отображение авторов

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
Route::get('/', 'DashboardController@dashboard')->name('admin.index');
Route::resource('/category', 'CategoryController', ['as'=>'admin']);
Route::resource('/article', 'ArticleController', ['as'=>'admin']);
Route::resource('/author', 'AuthorController', ['as'=>'admin']);
Route::resource('/role', 'RoleController', ['as'=>'admin']);
});


Route::group(['prefix'=>'blog'], function(){
    Route::get('/', 'BlogController@review')->name('blog.index');
    Route::resource('/review', 'ReviewController', ['as'=>'blog'] );
    });
    
// Route::post('/blog/review/create', 'ReviewController@create');

Route::get('/', function () {
    return view('blog.home');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{

    protected $table='roles';
    protected $primaryKey='id';
    protected $fillable = [
      'role_name', 'role_id'
    ];

    public function user()
  {
    return $this->hasMany('App\User');
  }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.roles.index', [
            'roles'=>Role::paginate(3)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create', [
            'role'=>[],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->all());
        $role->save();
        return redirect()->route('admin.role.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('admin.roles.edit', [
            'role'=>$role,
        ]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update($request->all());
        return redirect()->route('admin.role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);

        foreach ($role->user as $user){
            $user->role_id= NULL;
            $user->save();
        }

        $role->delete();
        return redirect()->route('admin.role.index');  
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if(auth()->user()->role_id == 2)
<h1 style="text-align:center;">Добавление роли</h1>
<div class="container">

<hr>

<form class="form-horizontal" action="{{route('admin.role.store')}}" method="post">
{{ csrf_field() }}

    @include('admin.roles.part.form_role')

</form>
</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if(auth()->user()->role_id == 2)
<div class="container">
<h1 style="text-align:center;">Редактирование роли</h1>
<hr>

<form class="form-horizontal" action="{{route('admin.role.update', $role)}}" method="post">
<input type="hidden" name="_method" value="PUT">
{{ csrf_field() }}

@include('admin.roles.part.form_role')

</form>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if(auth()->user()->role_id == 2)
<h1 style="text-align:center;">Добавление ролей</h1>
<div class="container" >

<a href="{{route('admin.role.create')}}" class="btn btn-primary pull-right">
    <i class="">Добавить роль</a>
    <table class="table table-striped">
        <thead>
        <th>ID</th>
            <th>Наименование</th>
            <th>Дата добавления</th>
            <th class="text-right">Действие</th>
</thead>
<tbody>
    @forelse ($roles as $role)
<tr>
<td> 
        {{$role->id}}
    </td>
    <td> 
        {{$role->role_name}}
    </td>
    <td> 
        {{$role->created_at}}
    </td>
    <td> 

    <div class="pull-right" style="">
          <a href="{{route('admin.role.edit', $role)}}" class="btn btn-primary">Редактирование</a>
     </div>

    <form onsubmit="if (confirm ('Удалить?') ) 
    { return true } 
    else 
    {return false}
    " action="{{route('admin.role.destroy', $role)}}" method="post">
    <input type="hidden" name="_method" value="DELETE">
    {{ csrf_field() }}

    <div class="pull-right" style="padding-right:10px;">
          <button type="submit" class="btn btn-primary">Удаление</button>
     </div>


    </form>
     
     
    </td>
</tr>
    @empty
<tr>
    <td colspan="4" class="text-center">
<h1>
    Данные отсутствуют
</h1>
</td>
</tr>
    @endforelse
</tbody>

<tfoot>
<tr>
<td colspan="4" class="text-center">
<ul class="pagination pull-center">
{{$roles->links()}}
</ul>
</td>
</tr>
</tfoot>
</table>
</a>

<div class="pull-left" style="padding-right:20px">
                <a href="/admin" class="btn btn-primary">Назад</a>
            </div>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection