routes/web.php
<?php

Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category'); //отобраэение категорий
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article'); // отображение новостей
Route::get('/blog/author/', 'BlogController@author')->name('author'); // отображение авторов

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
Route::get('/', 'DashboardController@dashboard')->name('admin.index');
Route::resource('/category', 'CategoryController', ['as'=>'admin']);
Route::resource('/article', 'ArticleController', ['as'=>'admin']);
Route::resource('/author', 'AuthorController', ['as'=>'admin']);
Route::resource('/role', 'RoleController', ['as'=>'admin']);
});


Route::group(['prefix'=>'blog'], function(){
    Route::get('/', 'BlogController@review')->name('blog.index');
    Route::resource('/review', 'ReviewController', ['as'=>'blog'] );
    });
    
// Route::post('/blog/review/create', 'ReviewController@create');

Route::get('/', function () {
    return view('blog.home');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{

    protected $primaryKey='id';

     protected $fillable = ['title', 'shortDescription',  'description', 'slug', 
     'category_id', 'meta_description', 'keyword', 'meta_title', 'image', 'user_id',
    ];

     public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), 
        '-');
      }

      public function category(){
        return $this->belongsTo('App\Category', 'category_id');
      }

      public function author(){
        return $this->belongsTo('App\User', 'user_id');
      }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $articles = Article::paginate(6);
        
        return view('admin.articles.index', ['articles' => $articles]);
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $categories = Category::all();
        $users = User::all();
        return view('admin.articles.create', ['categories' => $categories, 'users'=> $users]);
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'category_id' => 'required',
            'title' => 'required',
            'shortDescription',
            'description'=> 'required',
            'meta_title',
            'meta_description',
            'keyword',
            'slug' => 'readonly',
            'image',
            'user_id'=>'required',
		]);
		
            $article = new Article;
    
            $article->title = $request->title;
            $article->shortDescription = $request->shortDescription;
            $article->description = $request->description;
            $article->meta_description = $request->meta_description;
            $article->meta_title = $request->meta_title;
            $article->keyword = $request->keyword;
            $article->slug = $request->slug;
            $article->image = $request->image;
            $article->user_id = $request->user_id;
            $article->category_id = $request->category_id; 

            $article->save();
            return redirect()->route('admin.article.index');
        }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);
		return view('admin.articles.show', ['article' => $article]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function  edit($id)
    {
    
		$article = Article::find($id);	
        $categories = Category::all()->where('id', '<>', $article->category_id);
        $users = User::all()->where('id', '<>', $article->user_id);
        
        return view('admin.articles.edit', ['categories' => $categories,  'users'=> $users, 'article' => $article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
        $this->validate($request, [
            'category_id'=>'required',
            'title',
            'shortDescription',
            'description',
            'meta_title',
            'meta_description',
            'keyword',
            'image',
            'slug',
            // 'created_by'=>'required',
		]);
				
		$article = Article::find($id);
		
        $article->category_id = $request->category_id;
        $article->title = $request->title;
        $article->shortDescription = $request->shortDescription;
        $article->description = $request->description;
        $article->meta_title = $request->meta_title;
        $article->keyword = $request->keyword;
        $article->meta_description = $request->meta_description;
        $article->image = $request->image;
        // $article->created_by = $request->created_by;

		$article->save();
		return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
		$article->delete();
		return redirect()->route('admin.article.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))
<h1 style="text-align:center;">Создание статьи</h1>
<div class="container">
<hr>
<div>
<b class = "text-danger">  При написании статьи заполните поле "категория"</b>
</div>
<hr>

<form class="form-horizontal" action="{{ route('admin.article.store') }}" method="POST">
{{ csrf_field() }}

    @include('admin.articles.part.form')

<input type="hidden" name="user_id" value="{{Auth::id()}}">
</form>
</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or ((auth()->user()->role_id == 3) and ($user=Auth::user()->id == $article->user_id)))
<div class="container">
<h1 style="text-align:center;">Редактирование статьи</h1>
<hr>
<div>
<b class = "text-danger">  При редактировании статьи заполните поле "категория"</b>
</div>
<hr>


<form class="form-horizontal" action="{{route('admin.article.update', $article)}}" method="post">
<input type="hidden" name="_method" value="PUT">
{{ csrf_field() }}

@include('admin.articles.part.edit_art_form')

<!-- <input type="hidden" name="updated_by" value="{{Auth::id()}}"> -->

</form>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))
<h1 style="text-align:center;">Создание статей</h1>
<div class="container" >

<a href="{{route('admin.article.create')}}" class="btn btn-primary pull-right">
    <i class="">Создать статью</a>
    <table class="table table-striped">
        <thead>
            <th>Название статьи</th>
            <th>Категория</th>
            <th>Автор статьи</th>
            <th>Публикация</th>
            
            <th class="text-right">Действие</th>
</thead>
<tbody>
    @forelse ($articles as $article)
<tr>
    <td> 
        {{$article->title}}
    </td>
    <td> 
        {{$article->category->title or ""}}
    </td>
    <td> 
         {{$article->author->nickname or ""}}
    </td>
    <td> 
        {{$article->created_at}}
    </td>
    <td> 
    <div class="pull-right" style="padding:1px; margin:1px;">
          <a href="{{route('admin.article.show', $article)}}" class="btn btn-primary">Просмотр</a>
     </div>

    @if(($user=Auth::user()->id == $article->user_id) or (auth()->user()->role_id == 2))
    <div class="pull-right" style="padding:1px; margin:1px;">
          <a href="{{route('admin.article.edit', $article)}}" class="btn btn-primary">Редактирование</a>
     </div>
  
 
    <form onsubmit="if (confirm ('Удалить?') ) 
    { return true } 
    else 
    {return false}
    " action="{{route('admin.article.destroy', $article)}}" method="post">
    <input type="hidden" name="_method" value="DELETE">
    {{ csrf_field() }}

    <div class="pull-right" style="padding:1px; margin:1px;">
          <button type="submit" class="btn btn-primary">Удаление</button>
     </div>


    </form>
     
     @endif
    </td>
</tr>
    @empty
<tr>
    <td colspan="5" class="text-center">
<h1>
    Данные отсутствуют
</h1>
</td>
</tr>
    @endforelse
</tbody>

<tfoot>
<tr>
<td colspan="5" class="text-center">
<ul class="pagination pull-center">
{{$articles->links()}}
</ul>
</td>
</tr>
</tfoot>

</table>
</a>

<div class="pull-left" style="padding-right:20px">
                <a href="/admin" class="btn btn-primary">Назад</a>
            </div>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>{{$article->title}}</h1>
            <h3>Категория статьи: {{$article->category->title or ""}}</h3>
            <br>
            <p>{{$article->meta_title or ""}}</p>
            <p>{{$article->meta_description or ""}}</p>
            @if($article->keyword)
            <p>Ключевые слова: {{$article->keyword}}.</p>
            @else
            <p> Не нашлось подходящих ключевых слов.</p>
            @endif
            <br>
            <p>{{$article->shortDescription}}</p>
            <p>{{$article->description}}</p>
            @if($article->image)
            <img width="100%" height="100%" src="{{$article->image or ""}}" alt="Вложение"></img>   
            <br>      
                @else 
                <br>
                @endif
            <h4 class="font-italic">Кем подготовлена статья:
              @if($article->user_id == NULL)
                автор был удален.
                    @else 
                         {{$article->author->name or ""}}
                    @endif
             </h4>
            <a href="{{route('admin.article.store')}}" class="btn btn-primary">Назад</a>
        </div>
    </div>
</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection