routes/web.php
<?php

Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category'); //отобраэение категорий
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article'); // отображение новостей
Route::get('/blog/author/', 'BlogController@author')->name('author'); // отображение авторов

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
Route::get('/', 'DashboardController@dashboard')->name('admin.index');
Route::resource('/category', 'CategoryController', ['as'=>'admin']);
Route::resource('/article', 'ArticleController', ['as'=>'admin']);
Route::resource('/author', 'AuthorController', ['as'=>'admin']);
Route::resource('/role', 'RoleController', ['as'=>'admin']);
});


Route::group(['prefix'=>'blog'], function(){
    Route::get('/', 'BlogController@review')->name('blog.index');
    Route::resource('/review', 'ReviewController', ['as'=>'blog'] );
    });
    
// Route::post('/blog/review/create', 'ReviewController@create');

Route::get('/', function () {
    return view('blog.home');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{

    //parent не задействован
    protected $table='categories';
    protected $primaryKey='id';
    protected $fillable=['title', 'slug', 'created_by','updated_by', 'category_id']; 

    public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), 
        '-');
      }

      //категория - главная. одна категория - много статей.

      public function article(){
        return $this->hasMany('App\Article');
      }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categories.index', [
            'categories'=>Category::paginate(8)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create', [
            'category'=>[],
        ]); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $category = Category::create($request->all());
      $category->save();
      return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
       return view('admin.categories.edit', [
           'category'=>$category,

       ]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
       $category->update($request->all());
       return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);

        foreach ($category->article as $article){
            $article->delete();
        }
        $category->delete();
        return redirect()->route('admin.category.index');   
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))
<h1 style="text-align:center;">Создание категории</h1>
<div class="container">

<hr>

<form class="form-horizontal" action="{{route('admin.category.store')}}" method="post">
{{ csrf_field() }}

    @include('admin.categories.part.form')

</form>
</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))
<div class="container">
<h1 style="text-align:center;">Редактирование категории</h1>
<hr>

<form class="form-horizontal" action="{{route('admin.category.update', $category)}}" method="post">
<input type="hidden" name="_method" value="PUT">
{{ csrf_field() }}

@include('admin.categories.part.form')

</form>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
@if((auth()->user()->role_id == 2) or (auth()->user()->role_id == 3))
<h1 style="text-align:center;">Создание категорий</h1>
<div class="container" >

<a href="{{route('admin.category.create')}}" class="btn btn-primary pull-right">
    <i class="">Создать категорию</a>
    <table class="table table-striped">
        <thead>
            <th>Наименование</th>
            <th>Публикация</th>
            <th class="text-right">Действие</th>
</thead>
<tbody>
    @forelse ($categories as $category)
<tr>
    <td> 
        {{$category->title}}
    </td>
    <td> 
        {{$category->created_at}}
    </td>
    <td> 

    <div class="pull-right" style="">
          <a href="{{route('admin.category.edit', $category)}}" class="btn btn-primary">Редактирование</a>
     </div>
     @if(auth()->user()->role_id == 2)
    <form onsubmit="if (confirm ('Удалить?') ) 
    { return true } 
    else 
    {return false}
    " action="{{route('admin.category.destroy', $category)}}" method="post">
    <input type="hidden" name="_method" value="DELETE">
    {{ csrf_field() }}

    <div class="pull-right" style="padding-right:10px;">
          <button type="submit" class="btn btn-primary">Удаление</button>
     </div>


    </form>
     
     @endif
    </td>
</tr>
    @empty
<tr>
    <td colspan="3" class="text-center">
<h1>
    Данные отсутствуют
</h1>
</td>
</tr>
    @endforelse
</tbody>

<tfoot>
<tr>
<td colspan="3" class="text-center">
<ul class="pagination pull-center">
{{$categories->links()}}
</ul>
</td>
</tr>
</tfoot>
</table>
</a>

<div class="pull-left" style="padding-right:20px">
                <a href="/admin" class="btn btn-primary">Назад</a>
            </div>

</div>
@else
<div class="container" >

<h3>У вас недостаточно прав на просмотр данной страницы</h3>
<div class="pull-left" style="padding-right:20px">
                <a href="/" class="btn btn-primary">На главную</a>
            </div>

</div>
@endif
@endsection